Deleted keywords "virtual" where Keywords "override" is defined.
neoml-lib/neoml pull request #25
Opened 2020-06-22 10:08 UTC by ZigRazor

Following Guidelines rule C128 (ISSUE #17 Code style)

2020-06-25 11:21 UTC, FedyuninV commented on NeoMathEngine/src/CPU/CpuMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-25 11:23 UTC, FedyuninV commented on NeoMathEngine/src/GPU/CUDA/CudaMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-25 11:28 UTC, FedyuninV requested changes
Apologies for a delay in review.

Please, remove the rest of the `virtual`'s in Math Engines and then PR will be merged.

2020-06-25 11:28 UTC, FedyuninV commented on NeoMathEngine/src/GPU/Vulkan/VulkanMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-25 11:28 UTC, FedyuninV commented on NeoMathEngine/src/CPU/CpuMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-25 11:28 UTC, FedyuninV commented on NeoMathEngine/src/GPU/CUDA/CudaMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-25 11:28 UTC, FedyuninV commented on NeoMathEngine/src/GPU/Metal/MetalMathEngine.h
>  	virtual void VectorEqual( const CConstIntHandle& firstHandle, const CConstIntHandle& secondHandle,
In this file there're many multi-line function declarations. I think `virtual` should be removed there too.

But this file doesn't contain interfaces, that's why you can simply add `override` to destructor and remove `virtual` from the whole file.

2020-06-26 09:11 UTC, ZigRazor commented
I solved the requested change, so i request new review

2020-06-26 11:11 UTC, FedyuninV approved these changes
Thanks for contribution!

2020-06-26 11:11 UTC, merged