python comments
neoml-lib/neoml pull request #286
Opened 2021-03-22 11:36 UTC by valinurovdenis

Signed-off-by: valinurovdenis <denis.valinurow@yandex.ru>

2021-03-22 15:52 UTC, NadyaG requested changes
Не все комментарии переделаны. Недоделки в файлах:
* Activation
* Binarization

2021-03-25 07:56 UTC, NadyaG commented on NeoML/Python/neoml/Dnn/Ctc.py
> +    :param    loss_weight:  The multiplier for the loss function value during training.
extra spaces, might spoil the sphinx formatting?

2021-03-25 08:03 UTC, NadyaG approved these changes, later dismissed

2021-03-29 09:31 UTC, NadyaG approved these changes

2021-03-29 09:48 UTC, SAngeliuk approved these changes

2021-03-29 10:56 UTC, merged