Add Onnx2NeoML executable
neoml-lib/neoml pull request #507
Opened 2021-12-20 15:38 UTC by zimka

В PR добавляется простейшая исполняемая обертка вокруг NeoOnnx::LoadFromOnnx.

Сейчас NeoOnnx предоставляет программное api для конвертации Onnx в CDnn (NeoOnnx::LoadFromOnnx).
Т.к. NeoOnnx нельзя собрать вместе с FineObjects, использовать это api в проектах на основе FineObj сложно. Для конвертации onnx-сети приходится создавать новое временное приложение, что не очень удобно.
С другой стороны, в процессе конвертации нет никаких параметров/флагов/настроек, и, например, в tf2onnx [можно](https://github.com/onnx/tensorflow-onnx#getting-started) конвертировать и через cli, и через программный api.
Здесь по аналогии добавлен executable, который выполняет конвертацию. 
Протестировано на нейронке с одним Dense слоем.

2021-12-20 19:41 UTC, FedyuninV commented on NeoML/CMakeLists.txt
> +        list(APPEND INSTALLED_TARGETS NeoOnnx )
1) (мелочь) надо убрать пробел
2) (не мелочь) надо добавить эту утилиту в install. Как пример:
```
        if(TARGET Onnx2NeoML)
            list(APPEND INSTALLED_TARGETS Onnx2NeoML)
        endif()
```
или `NOT IOS NOT ANDROID`

2021-12-20 19:45 UTC, FedyuninV commented on NeoOnnx/src/CMakeLists.txt
> +    add_subdirectory(Onnx2NeoML)
(мелочь) Я бы перенес либо в выше (где-нибудь сразу после `add_library`) либо в самый низ. Иначе как-то неочевидно, что посередине CMake который описывает сборку NeoOnnx внезапно затесалась доп. утили.

2021-12-20 19:46 UTC, FedyuninV requested changes
Надо добавить утилиту в install.
Надо её расположить не внутри `src` а сбоку от `src` директории, на уровень выше.

2021-12-20 19:49 UTC, FedyuninV commented on NeoOnnx/src/CMakeLists.txt
> +    add_subdirectory(Onnx2NeoML)
Ой, вообще лучше всю утилиту вынести в отдельную поддиректорию на уровень выше! А этот if перенести NeoML/NeoOnnx/CMakeLists.txt

2021-12-21 14:03 UTC, zimka commented
Перенес утилиту на уровень выше (в NeoOnnx из NeoOnnx/src), добавил в install кроме мобилок

2021-12-22 13:25 UTC, FedyuninV approved these changes

2021-12-22 14:01 UTC, merged