Lstm
neoml-lib/neoml pull request #547
Opened 2022-01-24 20:13 UTC by yekatkov

2022-01-28 15:28 UTC, FedyuninV requested changes
Fix _critical_ comments plz. Fix _minor_ and _discussable_ if you wish.

2022-01-28 15:28 UTC, FedyuninV commented on NeoML/include/NeoML/Dnn/Layers/FullyConnectedLayer.h
> +	CPtr<CDnnBlob>& Weights() { return paramBlobs[0]; }
_[discussable]_

Mb `friend` class is better here? It doesn't look good in `public` together with `CPtr<CDnnBlob> GetWeightsData()`.

2022-01-28 15:28 UTC, FedyuninV commented on NeoML/include/NeoML/Dnn/Layers/LstmLayer.h
> +			if( lstmDesc ) {
_[minor, codestyle]_

We don't use implicit `if( notBoolValue )`. Only `if( bool )` or `if( value != 0 )` or `if( ptr != nullptr )`

2022-01-28 15:28 UTC, FedyuninV commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +		recurrentActivation == AF_Sigmoid ) {
_[minor, codestyle]_

Move `{` to the new line in case of multi-line condition.

2022-01-28 15:28 UTC, FedyuninV commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +		CConstFloatHandle inputFreeTermHandle, recurrentFreeTermHandle;
_[minor, codestyle]_

Multiple variables shouldn't be initialized in one line.

2022-01-28 15:28 UTC, FedyuninV commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +	lstmDesc = lstmLayer->MathEngine().InitLstm(
_[critical]_

Looks like a memory leak in the following scenarip:
- RunAndLearnOnce
- RunOnce (here first `CFastLstmDesc::lstmDesc` will be allocated)
- RunAndLearnOnce(here `Reshape()` will be called and `fastLstm.Reset()` will reset the `isInitialized` flag)
- RunOnce (here second `CFastLstmDesc::lstmDesc` will be allocated _without deleting the previous one_)

Better to run test with some memory leak detection to double check.
As a possible fix - delete lstmDesc on `CFastLstmDesc::Reset`

2022-01-28 15:28 UTC, FedyuninV commented on NeoMathEngine/src/CPU/CpuMathEngineDnnLstm.h
> +		int _hiddenSize, int _objectCount, int _objectSize, IMathEngine* _mathEngine, int _threadCount ) :
_[minor, codestyle]_

multiline argument list (if initializer list is present) offsets on _2 indents_.
every element of initializer list must be on a new line

```c++
CMyClass( long argumentList0, long argumentList1, long argumentList2, long argumentList3,
        long argumentList4, long argumentList5, long argumentList6, long argumentList7 ) :
    initializer0( argumentList0 ),
    initializer1( argumentList1 ),
    initializer2( argumentLis2 ),
    ...
```

2022-02-01 23:38 UTC, lordnn commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +	lstmDesc = lstmLayer->MathEngine().InitLstm(
`lstmDesc` deallocation will happens at `clearPointers()`

2022-02-03 17:38 UTC, yekatkov commented on NeoML/include/NeoML/Dnn/Layers/FullyConnectedLayer.h
> +	CPtr<CDnnBlob>& Weights() { return paramBlobs[0]; }
I think that `friend` class is also bad idea. If you worry about names that differ from copy implementation, I think that it is appropriate tradeoff between necessity to change all usage of renamed functions and just having two slight different in name functions. I suggest leaving it as is in PR. 
@SAngeliuk , your opinion?

2022-02-03 17:48 UTC, yekatkov commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +	lstmDesc = lstmLayer->MathEngine().InitLstm(
Exactly! The only place where lstm Desc is allocated has clearPointers() call before itself.

2022-02-04 08:06 UTC, SAngeliuk commented on NeoML/src/Dnn/Layers/LstmLayer.cpp
> +	if( lstmLayer->outputDescs.Size() != 2 ) {
If the current blob is enough you shouldn't do reallocations on Reshape().

2022-02-04 08:13 UTC, SAngeliuk commented on NeoMathEngine/src/CPU/CpuMathEngineDnnLstm.h
> +			mathEngine->VectorAdd( forgetData, inputData, outputStateBackLink + OffsetBackLink, CurDataSize );
No a omp call in a omp cycle! You should use vectorAdd here!

2022-02-07 11:15 UTC, SAngeliuk submitted a review, later dismissed

2022-02-08 12:22 UTC, FedyuninV approved these changes

2022-02-08 12:23 UTC, merged