Distributed fix
neoml-lib/neoml pull request #564
Opened 2022-02-14 18:01 UTC by valinurovdenis

2022-02-14 19:10 UTC, FedyuninV requested changes

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +    def __init__(self, dnn, type='cpu', count=0, devs=None, initializer='xavier', seed=42):
`raise ValueError` here if 
- `dnn` has wrong type
- `intitializer` has wrong value (only small set  of strings is valid)

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +    def run(self, set_data):
_[minor]_
`set_data` name isn't clear.
`data_setter` or `set_data_callback`

P.S. same goes for the `learn` and `run_and_backward`

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +            as an argument. It must return a dictionary of input blobs for the
_[minor]_ `as its arguments` (it takes 2 arguments)

P.S. same goes for the `learn` and `run_and_backward`

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +            learn method of a dnn.
_[minor]_ You mention `learn method of a dnn` in every comment. I think it's better to mention `run` in comment for `run`, `learn` for `learn`, etc.

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +    def get_model_count(self):
If you use `@property` it's better to name this method as `model_count`.

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +    def solver(self, path):
_[minor]_ It's a method (not a property), and it can't be decorated as a property. That's why let's name it `get_solver`

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/src/PyDnnDistributed.cpp
> +py::list CPyDistributedTraining::GetOutput( const std::string& layer )
_[discussion]_ Why do you use `py::list` here and `py::array` in the method above?

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/Python/src/PyDnnDistributed.h
> +    int GetModelCount_() { return GetModelCount(); }
What do you need it for? Why don't you use just `GetModelCount()`?

2022-02-14 19:10 UTC, FedyuninV commented on NeoML/include/NeoML/FineObjLite/MemoryFile.h
> +/* Copyright � 2017-2020 ABBYY Production LLC
Rename this file to `MemoryFileFOL.h`

2022-02-15 06:11 UTC, lordnn commented on NeoML/include/NeoML/FineObjLite/MemoryFile.h
> +	virtual void Flush();
Base class methods  should be marked as `override` not `virtual`.

2022-02-15 11:50 UTC, FedyuninV commented on NeoML/Python/neoml/Dnn/DnnDistributed.py
> +        .. rubric:: Layer outputs:
It isn't a layer.
The Sphinx has the `:rtype:` annotation for that cases.
+ In one case you return generator (or list?) in another - numpy array. That should be clarified too.
P.S. (same goes for get_last_losses)

2022-02-15 12:03 UTC, FedyuninV approved these changes, later dismissed

2022-02-15 12:07 UTC, lordnn commented on NeoML/include/NeoML/FineObjLite/MemoryFileFOL.h
> +	virtual ~CMemoryFileEx();
Деструктор - то-же метод базоваго класса, то-же - `override`.

2022-02-15 12:37 UTC, FedyuninV approved these changes

2022-02-15 12:41 UTC, merged