Update MultiheadAttention layer
neoml-lib/neoml pull request #651
Opened 2022-06-08 11:42 UTC by black-boomerang

Added mask type parameter and rebuild method

2022-06-23 17:12 UTC, NValerij commented on NeoML/include/NeoML/Dnn/Layers/TransformerSourceMaskLayer.h
> +// Tha layer that, based on a batch of widths and the shape of the matrix Q, builds a mask in multihead
Misprint.

2022-07-14 22:14 UTC, FedyuninV submitted a review, later dismissed

2022-07-20 16:49 UTC, FedyuninV requested changes
Double-check tests

2022-07-20 16:49 UTC, FedyuninV commented on NeoML/test/src/TransformerSourceMaskTest.cpp
> +/* Copyright © 2017-2022 ABBYY Production LLC
This file isn't mentioned in corresponding CMakeLists.txt. These tests won't be compiled (and the launched)

2022-08-12 12:49 UTC, FedyuninV approved these changes

2022-08-12 13:26 UTC, merged